apiVersion: v2
appVersion: 2.2.1
description: Helm chart for deploying Higress gateways
icon: https://higress.io/img/higress_logo_small.png
home: http://higress.io/
keywords:
- higress
- gateways
name: higress
sources:
- http://github.com/alibaba/higress
dependencies:
- name: higress-core
  repository: "file://../core"
  version: 2.2.0
  condition: higress-core.enabled
- name: higress-console
  alias: aigateway-console
  repository: "file://../../../higress-console/helm"
  version: 2.1.0
  condition: aigateway-console.enabled
- name: aigateway-portal
  repository: "file://../../../aigateway-portal/helm"
  version: 0.1.0
  condition: aigateway-portal.enabled
type: application
version: 2.2.1
